language: ruby
rvm:
  - 2.1.5
sudo: false

services:
  - postgresql

env:
  - BUILD_JOB=models
  - BUILD_JOB=rubocop

before_install:
  - echo 'before install'

install:
  - echo 'installing all the things'

before_script:
  - echo 'before script'
  - cp config/database-travis.yml config/database.yml
  - bundle exec rake db:create db:schema:load

script:
  - echo 'lets build this thing'
  - ci/travis.sh

notifications:
  emails:
    - alexkalish@gmail.com
